# 5DATA002W.2 Coursework - Final Python Notebook 1
**Author:** Thewan Jayaweera

**Peer Reviewer:** Sandes Damunugalla

**Date of Review:** 18/02/2026

**Reused from: Code Reuse Session 1 (Prompts 1, 18, 2)**

In [1]:
# Import pandas library to load and access the dataset
import pandas as pd

# Control the rows truncation when displaying the dataset
pd.set_option('display.max_rows', 500)

# Control the columns truncation when displaying the dataset
pd.set_option('display.max_columns', 500)

# Control the display width of the dataset
pd.set_option('display.width', 150)

# Load the dataset file
data = pd.read_csv('loan_approval_data.csv')

**Reused from: Code Reuse Session 1 (Prompt 3)**

In [2]:
# Access and display the recorded data values of 10 clients
data.head(10)

,id,age,income,home_ownership,emplyment_length,loan_intent,loan_amount,loan_interest_rate,loan_income_ratio,payment_default_on_file,credit_history_length,loan_approval_status,max_allowed_loan
0,35437,21.0,12000,OWN,0,EDUCATION,15000,6.99,0.12,N,4,0,-2426900
1,53756,21.0,13200,OWN,2,EDUCATION,25000,16.77,0.19,Y,3,0,-111739
2,42205,23.0,9600,RENT,5,MEDICAL,30000,12.42,0.31,N,3,0,-89000
3,19180,40.0,182004,RENT,3,EDUCATION,35000,8.00,0.19,N,11,0,35000
4,28072,40.0,90000,MORTGAGE,3,HOMEIMPROVEMENT,35000,12.42,0.39,N,14,0,35000
5,32074,40.0,131004,MORTGAGE,9,VENTURE,30000,7.90,0.23,N,13,0,30000
6,7224,40.0,150000,MORTGAGE,9,DEBTCONSOLIDATION,25000,11.89,0.17,N,11,0,25000
7,14471,40.0,132000,MORTGAGE,3,HOMEIMPROVEMENT,25000,16.82,0.22,N,17,0,25000
8,20163,40.0,80000,MORTGAGE,2,DEBTCONSOLIDATION,25000,10.25,0.31,N,11,0,25000
9,20384,40.0,80000,MORTGAGE,9,VENTURE,25000,18.67,0.30,N,17,0,25000

**Reused from: Code Reuse Session 1 (Prompt 4)**

In [3]:
# Display the variables names from the dataset
list(data.columns)

['id',
 'age',
 'income',
 'home_ownership',
 'emplyment_length',
 'loan_intent',
 'loan_amount',
 'loan_interest_rate',
 'loan_income_ratio',
 'payment_default_on_file',
 'credit_history_length',
 'loan_approval_status',
 'max_allowed_loan']

**Reused from: Code Reuse Session 1 (Prompt 5)**

In [4]:
# Explore the data types for all the variables in the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58645 entries, 0 to 58644
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       58645 non-null  int64
 1   age                      58639 non-null  float64
 2   income                   58645 non-null  int64
 3   home_ownership           58645 non-null  object
 4   emplyment_length         58645 non-null  int64
 5   loan_intent              58645 non-null  object
 6   loan_amount              58645 non-null  int64
 7   loan_interest_rate       58634 non-null  float64
 8   loan_income_ratio        58645 non-null  float64
 9   payment_default_on_file  58640 non-null  object
 10  credit_history_length    58645 non-null  int64
 11  loan_approval_status     58645 non-null  int64
 12  max_allowed_loan         58645 non-null  int64
dtypes: float64(3), int64(7), object(3)
memory usage: 5.8+ MB

**Reused from: Code Reuse Session 1 (Prompt 6)**

In [5]:
# Calculate and display the dimensions of the dataset (number of instances and features)
data.shape

(58645, 13)

**Reused from: Code Reuse Session 1 (Prompt 7)**

In [6]:
# Display the basic descriptive statistics for the numeric variables
data.describe()

,id,age,income,emplyment_length,loan_amount,loan_interest_rate,loan_income_ratio,credit_history_length,loan_approval_status,max_allowed_loan
count,58645.000000,58639.000000,5.864500e+04,58645.000000,58645.000000,58634.000000,58645.000000,58645.000000,58645.000000,5.864500e+04
mean,29322.000000,27.550913,6.404617e+04,4.703487,9217.556518,10.677526,0.159238,5.813556,0.142382,6.975472e+04
std,16929.497605,6.033217,3.793111e+04,4.004982,5563.807384,3.036034,0.091692,4.029196,0.349445,6.175091e+04
min,0.000000,20.000000,4.200000e+03,0.000000,500.000000,-11.140000,0.000000,2.000000,0.000000,-2.426900e+06
25%,14661.000000,23.000000,4.200000e+04,2.000000,5000.000000,7.880000,0.090000,3.000000,0.000000,3.800300e+04
50%,29322.000000,26.000000,5.800000e+04,4.000000,8000.000000,10.750000,0.140000,4.000000,0.000000,6.239200e+04
75%,43983.000000,30.000000,7.560000e+04,7.000000,12000.000000,12.990000,0.210000,8.000000,0.000000,9.271600e+04
max,58644.000000,123.000000,1.900000e+06,150.000000,35000.000000,23.220000,0.830000,30.000000,1.000000,2.638778e+06

**Reused from: Code Reuse Session 1 (Prompt 8)**

In [7]:
# Display the basic descriptive statistics for the categorical variables
data.describe(include='object')

       home_ownership loan_intent payment_default_on_file
count           58645       58645                   58640
unique              4           6                       2
top              RENT   EDUCATION                       N
freq            30594       12271                   49940

**Reused from: Code Reuse Session 1 (Prompt 9)**

In [8]:
# Show the distinct values for the loan_approval_status variable
data['loan_approval_status'].unique()

array([0, 1])

**Reused from: Code Reuse Session 1 (Prompts 13 & 14)**

In [9]:
# Import a Python package to visualise variables
import plotly.express as px

# Show the frequency distribution of age (numeric variable)
age_fig = px.histogram(data, x='age')

# Display the numeric variable frequency distribution figure
age_fig.show()

**Reused from: Code Reuse Session 1 (Prompt 15)**

In [10]:
# Show the frequency distribution of a categorical variable (Target variable = 'loan_approval_status')
loan_approval_status_fig = px.bar(data, x=data['loan_approval_status'].astype(str))

# Display the figure
loan_approval_status_fig.show()

**Reused from: Code Reuse Session 1 (Prompt 16)**

In [11]:
# Test clients' data with IQR in loan_interest_rate variable to discover outliers
loan_interest_rate_fig = px.box(data, x='loan_interest_rate')

# Display the box plot figure
loan_interest_rate_fig.show()

**Reused from: Code Reuse Session 1 (Prompt 10)**

In [12]:
# Show the count of clients who have missing values per variable
data.isnull().sum()

id                          0
age                         6
income                      0
home_ownership              0
emplyment_length            0
loan_intent                 0
loan_amount                 0
loan_interest_rate         11
loan_income_ratio           0
payment_default_on_file     5
credit_history_length       0
loan_approval_status        0
max_allowed_loan            0
dtype: int64

**Reused from: Code Reuse Session 1 (Prompt 11)**

In [13]:
# Calculate and display the percentage of clients with missing values per variable
data.isna().sum()/len(data)*100

id                         0.000000
age                        0.010231
income                     0.000000
home_ownership             0.000000
emplyment_length           0.000000
loan_intent                0.000000
loan_amount                0.000000
loan_interest_rate         0.018757
loan_income_ratio          0.000000
payment_default_on_file    0.008526
credit_history_length      0.000000
loan_approval_status       0.000000
max_allowed_loan           0.000000
dtype: float64

**Reused from: Code Reuse Session 1 (Prompts 21, 22)**

In [14]:
# Perform simple imputation by calculating the mean of loan_interest_rate variable
mean_loan_interest_rate = data['loan_interest_rate'].mean()

# Fill the missing values in the loan_interest_rate variable with the calculated mean (The new syntax was used as the old syntax is not supported in pandas 3.0)
data['loan_interest_rate'] = data['loan_interest_rate'].fillna(mean_loan_interest_rate)

# Perform a complete case analysis by dropping rows with any remaining missing data
data = data.dropna()

# Display missing values count after cleaning to confirm there are no missing values
data.isnull().sum()

id                         0
age                        0
income                     0
home_ownership             0
emplyment_length           0
loan_intent                0
loan_amount                0
loan_interest_rate         0
loan_income_ratio          0
payment_default_on_file    0
credit_history_length      0
loan_approval_status       0
max_allowed_loan           0
dtype: int64

**Reused from: Code Reuse Session 1 (Prompts 17 & 19)**

In [15]:
# Build a function to detect outliers in loan_interest_rate variable using the IQR
def find_outliers_IQR(data):

  # Calculate the first quartile (25th percentile)
  q1=data.quantile(0.25)

  # Calculate the third quartile (75th percentile)
  q3=data.quantile(0.75)

  # Calculate the Inter-Quartile Range
  IQR=q3-q1

  # Filter the data to find data points outside the defined boundaries
  outliers = data[((data<(q1-1.5*IQR)) | (data>(q3+1.5*IQR)))]

  # Return the detected outliers
  return outliers

# Call the built IQR function to detect outliers in loan_interest_rate variable
outliers = find_outliers_IQR(data['loan_interest_rate'])

# Print the total number of detected outliers
print("number of outliers: "+ str(len(outliers)))

# Display the detected outliers
outliers

number of outliers: 35

727      21.36
741      21.21
783      21.74
1478     23.06
1969     21.74
2123     21.36
2166     21.21
2837     20.86
2842     20.89
3198     20.69
3801     21.36
4232     20.86
4234     20.80
4815     21.21
6303     20.89
6550     23.22
7087     21.21
7442     21.21
8183     20.89
8562     21.36
8627     21.36
8630     21.36
8998    -11.14
10845    20.69
35364    20.89
36613    21.36
36949    21.74
37217    20.89
46452    22.06
47293    21.74
50909    20.69
52991    20.89
54223    21.36
57238    22.11
58150    21.64
Name: loan_interest_rate, dtype: float64

**Reused from: Code Reuse Session 1 (Prompt 20)**

In [16]:
# Remove the three most extreme outliers from the dataset using their index
data.drop([6550, 1478, 8998], inplace=True)

**Reused from: Code Reuse Session 1 (Prompt 16) - After removing the outliers**

In [17]:
# Plot the box-plot diagram for 'loan_interest_rate' again to check if the outliers have been removed
new_loan_interest_fig = px.box(data, x='loan_interest_rate')

# Display the box plot figure
new_loan_interest_fig.show()

**Reused from: Code Reuse Session 1 (Prompts 12, 23, 24, 25, 26)**

In [18]:
# Remove unnecessary variables
data = data.drop(columns=(['id', 'loan_income_ratio']))

# Map the categorical values 'Y' & 'N' to numerical format '0' & '1' for the model to process
data['payment_default_on_file'] = data['payment_default_on_file'].map({'N': 0 , 'Y': 1})

# Convert float variable 'age' into an integer data type as the decimal precision is not important
data = data.astype({"age":"int"})

# Import the preprocessing package from sklearn to encode ordinal columns into numeric labels
from sklearn import preprocessing

# Initialize the LabelEncoder
label_encoder = preprocessing.LabelEncoder()

# Apply the method to encode the object type variables
data['home_ownership'] = label_encoder.fit_transform(data['home_ownership'])
data['loan_intent'] = label_encoder.fit_transform(data['loan_intent'])

**Reused from: Code Reuse Session 1 (Prompts 12, 29, 30, 32, 33, 28, 27)**

In [19]:
# Group the numeric features into one variable
numeric_cols = ['age', 'income', 'emplyment_length', 'loan_amount', 'loan_interest_rate', 'credit_history_length']

# Group the categorical features into one variable
categorical_cols = ['home_ownership', 'loan_intent', 'payment_default_on_file']

# Import the MinMaxScaler package
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Apply Minimum-Maximum Scaling to the numeric columns
data[numeric_cols] = scaler.fit_transform(data[numeric_cols])

# Reuse prompt 12 to remove regression target before saving the classification report
classification_data = data.drop(columns=['max_allowed_loan'])

# Save the prepared classification dataset in a CSV file
classification_data.to_csv(r'Classification_Loan_Data.csv', index=False)

# Isolate the clients who were approved for a loan
regression_data=data[data.loan_approval_status == 0]

# Save the prepared regression dataset in a CSV file
regression_data.to_csv(r'Regression_Loan_Data.csv', index=False)

In [20]:
# Output the dimensions of the retained regression dataset
print("Dataset Dimensions:", regression_data.shape)

# Output the list of the retained feature names
print("\nRetained Features List:")
print(regression_data.columns.tolist())

Dataset Dimensions: (50285, 11)

Retained Features List:
['age', 'income', 'home_ownership', 'emplyment_length', 'loan_intent', 'loan_amount', 'loan_interest_rate', 'payment_default_on_file', 'credit_history_length', 'loan_approval_status', 'max_allowed_loan']